# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [4]:
import numpy as np
print (np.__version__)

1.26.4


#### 3. Create a null vector of size 10

In [6]:
import numpy as np
arr=np.zeros(10)
print (arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [11]:
import numpy as np
arr=np.array([1,2,3,4,5])
print (arr.size) #number of values in the array
print (arr.nbytes) # number of space or bytes consumed


5
20


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [15]:
arr.shape?


Type:        tuple
String form: (5,)
Length:      1
Docstring:  
Built-in immutable sequence.

If no argument is given, the constructor returns an empty tuple.
If iterable is specified the tuple is initialized from iterable's items.

If the argument is a tuple, the return value is the same object.

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [17]:
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [19]:
d=np.linspace(10,49,10)
print(d)

[10.         14.33333333 18.66666667 23.         27.33333333 31.66666667
 36.         40.33333333 44.66666667 49.        ]


#### 8.  Reverse a vector (first element becomes last)

In [23]:
# pp=np.reverse(d)
# print(pp) this is wrong as reverse is not there so we will prefer slicing

temp=d[::-1]  # prefering slicing as it will revrese our array easily using ::-1
print(temp)

[49.         44.66666667 40.33333333 36.         31.66666667 27.33333333
 23.         18.66666667 14.33333333 10.        ]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [26]:
temp=np.linspace(0,8,9)
print("array without arranging",temp)

new_temp=temp.reshape(3,3)
print("after reshaping into 3*3  matrix \n", new_temp)

array without arranging [0. 1. 2. 3. 4. 5. 6. 7. 8.]
after reshaping into 3*3  matrix 
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [ ]:
cond=

#### 11. Create a 3x3 identity matrix

#### 12. Create a 3x3x3 array with random values

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

#### 14. Create a random vector of size 30 and find the mean value

#### 15. Create a 2d array with 1 on the border and 0 inside

#### 16. How to add a border (filled with 0's) around an existing array?

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?